nginx:
    build: ./nginx
    links:
        - stream:stream
        - tracker:tracker
    ports:
        - "80:80"
tracker:
    image: tutum/haproxy
    links:
        - stream
    ports:
        - "5000:80"
    environment:
        - BACKEND_PORT=8080
        - BALANCE=roundrobin

stream:
    image: ndrd/centos-node
    links:
        - redis
    ports:
        - "8080"
redis:
    image: redis
    ports:
        - "6379"
