nginx:
    build: ./nginx
    links:
        - node1:node1
        - node2:node2
    ports:
        - "80:80"
node1:
    image: ndrd/centos-node
    links:
        - redis
    ports:
        - "8080"
node2:
    image: ndrd/centos-node
    links:
        - redis
    ports:
        - "8080"
redis:
    image: redis
    ports:
        - "6379"
