nginx:
    build: ./nginx
    links:
        - stream:stream
    ports:
        - "80:80"
stream:
    image: ndrd/centos-node
    links:
        - redis
    ports:
        - "8080"
redis:
    image: redis
    ports:
        - "6379"
